spring:
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
server:
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
  port: 9090

mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml